[package]
name = "rust-automations"
version = "0.1.0"
edition = "2024"

[dependencies]
thirtyfour = "0.35.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
chromiumoxide = "0.8.0"
futures = "0.3.31"
dotenvy = "0.15.7"
chrono = "0.4.43"
headless_chrome = "1.0.20"
